# -*- coding: utf-8 -*-
"""CoolingTowerDetectionUsingYOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CfcM0vjbIDvty5QU6WbUPaTzfU8K8vPs

-Kanishka Dubey
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CoolingtowerProject
!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CoolingtowerProject/yolov5

!pip install -qr requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CoolingtowerProject/yolov5/
import torch
from yolov5 import utils
import torch
import utils
from IPython import display
from IPython.display import clear_output
from pathlib import Path
import yaml
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import glob


# %matplotlib inline
display = utils.notebook_init()

# Commented out IPython magic to ensure Python compatibility.
#create dataset folder and split it into train, valid, test folder
# %cd /content/drive/MyDrive/CoolingtowerProject

def create_folders(name):
    Path(f"/content/drive/MyDrive/CoolingtowerProject/{name}/images/train").mkdir(parents=True, exist_ok=True)
    Path(f"/content/drive/MyDrive/CoolingtowerProject/{name}/images/valid").mkdir(parents=True, exist_ok=True)
    Path(f"/content/drive/MyDrive/CoolingtowerProject/{name}/images/test").mkdir(parents=True, exist_ok=True)
    Path(f"/content/drive/MyDrive/CoolingtowerProject/{name}/labels/train").mkdir(parents=True, exist_ok=True)
    Path(f"/content/drive/MyDrive/CoolingtowerProject/{name}/labels/valid").mkdir(parents=True, exist_ok=True)
    Path(f"/content/drive/MyDrive/CoolingtowerProject/{name}/labels/test").mkdir(parents=True, exist_ok=True)

    
create_folders('CoolingTower_dataset')

#contents of CoolingTower.yaml file
!cat /content/drive/MyDrive/CoolingtowerProject/yolov5/data/CoolingTower.yaml
print ('---------------------------------------------')

"""## <font color=2562A8>Training</font>"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CoolingtowerProject/yolov5
!python train.py --batch 32 --epochs 300 --data "/content/drive/MyDrive/CoolingtowerProject/yolov5/data/CoolingTower.yaml" --weights '' --cfg "/content/drive/MyDrive/CoolingtowerProject/yolov5/models/yolov5s.yaml" --cache --name 'yolov5s'

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CoolingtowerProject/yolov5
!python train.py --batch 32 --epochs 500 --data "/content/drive/MyDrive/CoolingtowerProject/yolov5/data/CoolingTower.yaml" --weights '' --cfg "/content/drive/MyDrive/CoolingtowerProject/yolov5/models/hub/yolov5s6.yaml" --cache --name 'yolov5s6'

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/CoolingtowerProject/yolov5
!python train.py --batch 32 --epochs 600 --data "/content/drive/MyDrive/CoolingtowerProject/yolov5/data/CoolingTower.yaml" --weights '' --cfg "/content/drive/MyDrive/CoolingtowerProject/yolov5/models/yolov5m.yaml" --cache --name 'yolov5m'

#Validation

!python val.py --batch 32 --data '/content/drive/MyDrive/CoolingtowerProject/yolov5/data/CoolingTower.yaml' --weights '/content/drive/MyDrive/CoolingtowerProject/yolov5/runs/train/yolov5s3/weights/best.pt' --iou-thres 0.6

#Validation

!python val.py --batch 32 --data '/content/drive/MyDrive/CoolingtowerProject/yolov5/data/CoolingTower.yaml' --weights '/content/drive/MyDrive/CoolingtowerProject/yolov5/runs/train/yolov5s6/weights/best.pt' --iou-thres 0.6
#clear_output()

#Validation

!python val.py --batch 32 --data '/content/drive/MyDrive/CoolingtowerProject/yolov5/data/CoolingTower.yaml' --weights '/content/drive/MyDrive/CoolingtowerProject/yolov5/runs/train/yolov5s6/weights/best.pt' --task test

#Validation

!python val.py --batch 32 --data '/content/drive/MyDrive/CoolingtowerProject/yolov5/data/CoolingTower.yaml' --weights '/content/drive/MyDrive/CoolingtowerProject/yolov5/runs/train/yolov5s3/weights/best.pt' --task test

#Inference

!python detect.py --weights '/content/drive/MyDrive/CoolingtowerProject/yolov5/runs/train/yolov5s6/weights/best.pt'  --conf 0.6 --iou 0.45 --source '/content/drive/MyDrive/CoolingtowerProject/CoolingTower_dataset/images/test' --name 'detect_test' --augment
#clear_output()

"""Thank You !!"""